---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "mysql_root_password"
mysql_db: "wordpress"
mysql_user: "smantilla"
mysql_password: "Senplades2o18"

#HTTP Settings
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"

#POSTGRESQL Settings
postgresql_db: "wordpress"
postgresql_user: "wordpress"
postgresql_password: "Admin.123"
postgres_host: ""